name: Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    concurrency:
      group: docker-publish-arm-${{ github.ref_name }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/create-github-app-token@v2
        name: Create GitHub App Token
        id: app-token
        with:
          app-id: ${{ vars.ARGO_APP_ID }}
          private-key: ${{ secrets.ARGO_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            oxy-internal
            oxy-internal-build

      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: oxy-hq/oxy-internal
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max_old_space_size
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/oxy-internal-build:latest
            ghcr.io/${{ github.repository_owner }}/oxy-internal-build:${{ steps.checkout.outputs.commit }}
